### ISSUE TITLE
The requirements are incorrect and some files are missing.

### ISSUE THREAD

**Issue by zhiqing0205** [MichaelHopwood/ForwardForwardOneclass#1]
The requirements.txt file contains over **two hundred** lines, which is definitely incorrect, and many of them are pointing to directories on your local machine. Running the installation dependencies directly will definitely cause problems. Also, the ** "scripts" folder **mentioned in the code is not visible within the project. If you really want someone else to fully reproduce the code and upload it to GitHub, you should make sure they can access everything accurately.

**Comment by MichaelHopwood** [comment]
Hey, thanks for your feedback! The implementation was rushed as this work was originally just meant for a class project. I'll address reproducibility issues here shortly :)

**Comment by MichaelHopwood** [comment]
@zhiqing0205 Let me know if you have any issues. I just did a clean clone and addressed the minor issues.

**Comment by zhiqing0205** [comment]
Thank you very much for taking the time to modify your code. I will carefully review it and provide positive feedback.
